apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-server
  template:
    metadata:
      labels:
        app: employee-server
    spec:
      containers:
       - image: ##############
         name: employee-server
         ports:
           - containerPort: 8445
         env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: #########
            - name: SPRING_DATASOURCE_URL
              value: ############
            - name: SPRING_DATASOURCE_USERNAME
              value: ##########
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update